### ISSUE TITLE
Safecharge URLS

### ISSUE THREAD

**Issue by giwrgos88** [mfauveau/omnipay-safecharge#1]
Why you are using https://test.safecharge.com/service.asmx/Process? instead of https://secure.SafeCharge.com/ppp/purchase.do? 

Thank you

**Comment by mfauveau** [comment]
This is for SafeCharge Direct Gateway, not the "Cashier" (which is just like Gate2Shop @see https://github.com/mfauveau/omnipay-gate2shop).
